### ISSUE TITLE
Requiring namespace 'Gdk' version '3.0', but '4.0' is already loaded

### ISSUE THREAD

**Issue by Miuler** [CeroProgramming/ulauncher-pulsecontrol#1]
I have the next error:

```
Sep 11 11:02:11 LIM-B68SPN2 /usr/lib/gdm-wayland-session[283958]: file:///usr/share/ulauncher/preferences/dist/static/js/app.c7a36559c1151f811a88.js:4919:18: CONSOLE ERROR TypeError: e.cancel is not a function. (In 'e.cancel()', 'e.cancel' is undefined)
Sep 11 11:02:14 LIM-B68SPN2 /usr/lib/gdm-wayland-session[1964]: 2020-09-11 11:02:14,797 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.ceroprogramming.ulauncher-pulsecontrol" exited instantly with code 1
Sep 11 11:02:14 LIM-B68SPN2 /usr/lib/gdm-wayland-session[1964]: 2020-09-11 11:02:14,797 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.ceroprogramming.ulauncher-pulsecontrol" failed with an error: ImportError: Requiring namespace 'Gdk' version '3.0', but '4.0' is already loaded
```

```
Sep 11 11:02:27 LIM-B68SPN2 /usr/lib/gdm-wayland-session[285707]: method return time=1599840147.140305 sender=:1.30 -> destination=:1.900 serial=46 reply_serial=2
Sep 11 11:03:08 LIM-B68SPN2 /usr/lib/gdm-wayland-session[1964]: 2020-09-11 11:03:08,340 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. KeyError: 'com.github.ceroprogramming.ulauncher-pulsecontrol'
Sep 11 11:03:08 LIM-B68SPN2 /usr/lib/gdm-wayland-session[1964]: Traceback (most recent call last):
Sep 11 11:03:08 LIM-B68SPN2 /usr/lib/gdm-wayland-session[1964]:   File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
Sep 11 11:03:08 LIM-B68SPN2 /usr/lib/gdm-wayland-session[1964]:     resp = rt.dispatch(self, scheme_request.get_uri())
Sep 11 11:03:08 LIM-B68SPN2 /usr/lib/gdm-wayland-session[1964]:   File "/usr/lib/python3.8/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
Sep 11 11:03:08 LIM-B68SPN2 /usr/lib/gdm-wayland-session[1964]:     return callback(context, url_params)
Sep 11 11:03:08 LIM-B68SPN2 /usr/lib/gdm-wayland-session[1964]:   File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 436, in prefs_extension_update_prefs
Sep 11 11:03:08 LIM-B68SPN2 /usr/lib/gdm-wayland-session[1964]:     controller = ExtensionServer.get_instance().get_controller(ext_id)
Sep 11 11:03:08 LIM-B68SPN2 /usr/lib/gdm-wayland-session[1964]:   File "/usr/lib/python3.8/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
Sep 11 11:03:08 LIM-B68SPN2 /usr/lib/gdm-wayland-session[1964]:     return self.controllers[extension_id]
Sep 11 11:03:08 LIM-B68SPN2 /usr/lib/gdm-wayland-session[1964]: KeyError: 'com.github.ceroprogramming.ulauncher-pulsecontrol'
```

**Comment by CeroProgramming** [comment]
Hey, thanks for the report! 
I think the second part is just the consequence of the first error.
Anyway, I am not really able to reproduce the error yet. Can you quickly tell me distribution and version you are using? 
Wayland, gnome and python3.8 are obvious from the log :)
If you can think of anything else important to reproduce the error I am glad if you share! 

Thanks and regards,
Simon

**Comment by Miuler** [comment]
My distribution is arch linux, but I already found the solution, I had installed gtk4-git, I already removed it and everything works fine
